import { type NextPage } from "next";
import Head from "next/head";

import "@uiw/react-md-editor/markdown-editor.css";
import "@uiw/react-markdown-preview/markdown.css";
import { trpc } from "../../utils/trpc";
import { useRouter } from "next/router";
import Question from "../../components/Question";
import Answer from "../../components/Answer";

const Home: NextPage = () => {
  const {
    query: { id },
  } = useRouter();

  const question = trpc.question.getById.useQuery({ id: String(id) });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] p-10">
        <div className={"w-[80vw]"}>
          {question.data ? (
            <>
              <Question
                text={question.data.text}
                firstName={question.data.user.firstName}
                lastName={question.data.user.lastName}
                img={question.data.user.img}
              />
              <ul className={"ml-10"}>
                {question.data.answers.map(
                  ({
                    id,
                    text,
                    likes,
                    ekolikes,
                    dislikes,
                    user: { firstName, lastName, img },
                  }) => (
                    <li className={"mt-10"} key={id}>
                      <Answer
                        text={text}
                        id={id}
                        img={img}
                        firstName={firstName}
                        lastName={lastName}
                        likes={likes}
                        dislikes={dislikes}
                        ecolikes={ekolikes}
                        onUpdate={() => {
                          question.refetch();
                        }}
                      />
                    </li>
                  )
                )}
              </ul>
            </>
          ) : (
            <>loading</>
          )}
        </div>
      </main>
    </>
  );
};

export default Home;
