import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

import Question from "../components/Question";

const Home: NextPage = () => {
  const questions = trpc.question.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] p-10">
        {questions.data ? (
          <ul className={"w-[80vw]"}>
            {questions.data.map(
              ({ id, text, user: { firstName, lastName, img } }) => {
                return (
                  <li className={"mb-5"} key={id}>
                    <Link href={`question/${id}`}>
                      <Question
                        text={text}
                        img={img}
                        firstName={firstName}
                        lastName={lastName}
                      />
                    </Link>
                  </li>
                );
              }
            )}
          </ul>
        ) : (
          <>loading</>
        )}
      </main>
    </>
  );
};

export default Home;
